# Generated by Django 3.1.1 on 2020-11-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx1moneytrack', '0004_auto_20201101_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrogasto',
            name='owner',
            field=models.CharField(default='G', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrogasto',
            name='type',
            field=models.CharField(default='PUB', max_length=50),
            preserve_default=False,
        ),
    ]
