# Generated by Django 3.1.1 on 2021-02-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appz0projects', '0003_auto_20210223_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user2',
            new_name='user',
        ),
    ]
