# Generated by Django 3.1 on 2020-10-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx1moneytrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrogasto',
            name='category',
            field=models.CharField(choices=[('1', 'comida'), ('2', 'despensa'), ('3', 'pagosservicios'), ('4', 'pagosextras')], default='null', max_length=50),
            preserve_default=False,
        ),
    ]
