# Generated by Django 3.1 on 2020-11-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx1moneytrack', '0002_registrogasto_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrogasto',
            name='category',
            field=models.CharField(max_length=1),
        ),
    ]
