# Generated by Django 3.1 on 2020-11-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx1moneytrack', '0003_auto_20201101_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrogasto',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
