# Generated by Django 3.1.1 on 2020-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registroproyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('mainimage', models.CharField(max_length=50)),
                ('image1', models.CharField(max_length=50)),
                ('image2', models.CharField(max_length=50)),
                ('image3', models.CharField(max_length=50)),
                ('image4', models.CharField(max_length=50)),
                ('image5', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
