# Generated by Django 3.1.1 on 2020-11-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz1gman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='image1',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='image2',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='image3',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='image4',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='image5',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='mainimage',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
