# Generated by Django 3.1.1 on 2020-11-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz1gman', '0002_auto_20201123_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproyecto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='mainimage',
            field=models.ImageField(default='null', upload_to='projects'),
        ),
    ]
