# Generated by Django 3.1.1 on 2020-11-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz1gman', '0003_auto_20201126_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroproyecto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='registroproyecto',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='registroproyecto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='registroproyecto',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
