# Generated by Django 3.1.1 on 2020-11-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz1gman', '0006_auto_20201126_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
