# Generated by Django 3.1.1 on 2020-11-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz1gman', '0007_auto_20201126_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='description',
            field=models.CharField(max_length=120),
        ),
    ]
