# Generated by Django 3.1.1 on 2020-11-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz1gman', '0008_auto_20201130_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='image1',
            field=models.ImageField(default='null', upload_to='projectsgman'),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='image2',
            field=models.ImageField(default='null', upload_to='projectsgman'),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='image3',
            field=models.ImageField(default='null', upload_to='projectsgman'),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='image4',
            field=models.ImageField(default='null', upload_to='projectsgman'),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='image5',
            field=models.ImageField(default='null', upload_to='projectsgman'),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='mainimage',
            field=models.ImageField(default='null', upload_to='projectsgman'),
        ),
    ]
