# Generated by Django 3.1.1 on 2020-12-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz1gman', '0010_auto_20201209_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproyecto',
            name='category',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
