# Generated by Django 3.1.1 on 2020-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz1gman', '0011_registroproyecto_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='image1',
            field=models.ImageField(default='none', upload_to='projectsgman'),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='image2',
            field=models.ImageField(default='none', upload_to='projectsgman'),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='image3',
            field=models.ImageField(default='none', upload_to='projectsgman'),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='image4',
            field=models.ImageField(default='none', upload_to='projectsgman'),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='image5',
            field=models.ImageField(default='none', upload_to='projectsgman'),
        ),
    ]
