# Generated by Django 3.1 on 2020-12-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz1gman', '0013_auto_20201211_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='description',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
