# Generated by Django 3.1.1 on 2020-12-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz1gman', '0016_finalregistroproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalregistroproyecto',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
