# Generated by Django 3.1.1 on 2020-12-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appz1gman', '0017_finalregistroproyecto_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalregistroproyecto',
            name='next',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finalregistroproyecto',
            name='prev',
            field=models.IntegerField(default=0),
        ),
    ]
